export default {

  // login
  REQUEST_INITIATE: 'REQUEST_INITIATE',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOG_OUT: 'LOG_OUT',

  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_SUCCESS_AFTER: 'GET_PROFILE_SUCCESS_AFTER',
  GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',
  PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  PROFILE_UPDATE_FAIL: 'PROFILE_UPDATE_FAIL',

  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',

  REQUEST_BOOKINGS: 'REQUEST_BOOKINGS',

  LOADER_START: 'LOADER_START',
  LOADER_STOP: 'LOADER_STOP',
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',


  FORGET_PASSWORD_CODE_SEND_SUCCESS: 'FORGET_PASSWORD_CODE_SEND_SUCCESS',
  FORGET_PASSWORD_CODE_SEND_FAIL: 'FORGET_PASSWORD_CODE_SEND_FAIL',
  FORGET_PASSWORD_CODE_VERIFY_SUCCESS: 'FORGET_PASSWORD_CODE_VERIFY_SUCCESS',
  FORGET_PASSWORD_CODE_VERIFY_FAIL: 'FORGET_PASSWORD_CODE_VERIFY_FAIL',
  PASSWORD_RESET_SUCCESS: 'CONSTANTS.PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAIL: 'PASSWORD_RESET_FAIL',
  RESET_ALL_STATE: 'RESET_ALL_STATE',


  GET_INCOMING_PATIENTS_SUCCESS: 'GET_INCOMING_PATIENTS_SUCCESS',
  GET_INCOMING_PATIENTS_FAIL: 'GET_INCOMING_PATIENTS_FAIL',

};
