export default {

  // login
  REQUEST_INITIATE: 'REQUEST_INITIATE',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOG_OUT: 'LOG_OUT',

  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_SUCCESS_AFTER: 'GET_PROFILE_SUCCESS_AFTER',
  GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',
  PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  PROFILE_UPDATE_FAIL: 'PROFILE_UPDATE_FAIL',

  GET_CUSTOMER_SUCCESS: 'GET_CUSTOMER_SUCCESS',
  GET_CUSTOMER_FAIL: 'GET_CUSTOMER_FAIL',

  GET_DRIPORTER_LOCATION_SUCCESS: 'GET_DRIPORTER_LOCATION_SUCCESS',
  GET_DRIPORTER_LOCATION_FAIL: 'GET_DRIPORTER_LOCATION_FAIL',

  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  ADD_USER_FAIL: 'ADD_USER_FAIL',
  ADD_USER_SUCCESS_AFTER: 'ADD_USER_SUCCESS_AFTER',

  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAIL: 'GET_USER_FAIL',

  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',

  REQUEST_BOOKINGS: 'REQUEST_BOOKINGS',

  LOADER_START: 'LOADER_START',
  LOADER_STOP: 'LOADER_STOP',
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',

  ADD_VEHICLE_SUCCESS: 'ADD_VEHICLE_SUCCESS',
  ADD_VEHICLE_FAIL: 'ADD_VEHICLE_FAIL',
  GET_VEHICLE_SUCCESS: 'GET_VEHICLE_SUCCESS',
  GET_VEHICLE_FAIL: 'GET_VEHICLE_FAIL',
  GET_VEHICLE_PROFILE_SUCCESS: 'GET_VEHICLE_PROFILE_SUCCESS',
  GET_VEHICLE_PROFILE_FAIL: 'GET_VEHICLE_PROFILE_FAIL',
  UPDATE_VEHICLE_SUCCESS: 'UPDATE_VEHICLE_SUCCESS',
  UPDATE_VEHICLE_FAIL: 'UPDATE_VEHICLE_FAIL',
  CLEAR_VEHICLE_PROFILE: 'CLEAR_VEHICLE_PROFILE',
  ASSIGN_VEHICLE_SUCCESS: 'ASSIGN_VEHICLE_SUCCESS',
  ASSIGN_VEHICLE_FAIL: 'ASSIGN_VEHICLE_FAIL',
  ADD_OPSPORTER_SUCCESS: 'ADD_OPSPORTER_SUCCESS',
  ADD_OPSPORTER_FAIL: 'ADD_OPSPORTER_FAIL',
  GET_OPSPORTER_SUCCESS: 'GET_OPSPORTER_SUCCESS',
  GET_OPSPORTER_FAIL: 'GET_OPSPORTER_FAIL',
  GET_OPSPORTER_PROFILE_SUCCESS: 'GET_OPSPORTER_PROFILE_SUCCESS',
  GET_OPSPORTER_PROFILE_FAIL: 'GET_OPSPORTER_PROFILE_FAIL',
  UPDATE_OPSPORTER_SUCCESS: 'UPDATE_OPSPORTER_SUCCESS',
  UPDATE_OPSPORTER_FAIL: 'UPDATE_OPSPORTER_FAIL',

  ADD_DRIPORTER_SUCCESS: 'ADD_DRIPORTER_SUCCESS',
  ADD_DRIPORTER_FAIL: 'ADD_DRIPORTER_FAIL',
  GET_DRIPORTER_SUCCESS: 'GET_DRIPORTER_SUCCESS',
  GET_DRIPORTER_FAIL: 'GET_DRIPORTER_FAIL',
  GET_DRIPORTER_PROFILE_SUCCESS: 'GET_DRIPORTER_PROFILE_SUCCESS',
  GET_DRIPORTER_PROFILE_FAIL: 'GET_DRIPORTER_PROFILE_FAIL',
  UPDATE_DRIPORTER_SUCCESS: 'UPDATE_DRIPORTER_SUCCESS',
  UPDATE_DRIPORTER_FAIL: 'UPDATE_DRIPORTER_FAIL',

  ADD_HOTEL_STAFF_SUCCESS: 'ADD_HOTEL_STAFF_SUCCESS',
  ADD_HOTEL_STAFF_FAIL: 'ADD_HOTEL_STAFF_FAIL',
  GET_HOTEL_STAFF_SUCCESS: 'GET_HOTEL_STAFF_SUCCESS',
  GET_HOTEL_STAFF_FAIL: 'GET_HOTEL_STAFF_FAIL',
  GET_HOTEL_STAFF_PROFILE_SUCCESS: 'GET_HOTEL_STAFF_PROFILE_SUCCESS',
  GET_HOTEL_STAFF_PROFILE_FAIL: 'GET_HOTEL_STAFF_PROFILE_FAIL',
  UPDATE_HOTEL_STAFF_SUCCESS: 'UPDATE_HOTEL_STAFF_SUCCESS',
  UPDATE_HOTEL_STAFF_FAIL: 'UPDATE_HOTEL_STAFF_FAIL',

  ADD_HOTEL_PARTNER_SUCCESS: 'ADD_HOTEL_PARTNER_SUCCESS',
  ADD_HOTEL_PARTNER_FAIL: 'ADD_HOTEL_PARTNER_FAIL',
  ADD_HOTEL_PARTNER_SUCCESS_AFTER: 'ADD_HOTEL_PARTNER_SUCCESS_AFTER',
  EDIT_HOTEL_PARTNER_SUCCESS: 'EDIT_HOTEL_PARTNER_SUCCESS',
  EDIT_HOTEL_PARTNER_FAIL: 'EDIT_HOTEL_PARTNER_FAIL',
  EDIT_HOTEL_PARTNER_SUCCESS_AFTER: 'EDIT_HOTEL_PARTNER_SUCCESS_AFTER',
  GET_HOTEL_PARTNER_SUCCESS: 'GET_HOTEL_PARTNER_SUCCESS',
  GET_HOTEL_PARTNER_FAIL: 'GET_HOTEL_PARTNER_FAIL',
  GET_HOTEL_PARTNER_SUCCESS_AFTER: 'GET_HOTEL_PARTNER_SUCCESS_AFTER',

  ADD_HOTEL_BOOKING_SUCCESS: 'ADD_HOTEL_BOOKING_SUCCESS',
  ADD_HOTEL_BOOKING_FAIL: 'ADD_HOTEL_BOOKING_FAIL',
  ADD_HOTEL_BOOKING_SUCCESS_AFTER: 'ADD_HOTEL_BOOKING_SUCCESS_AFTER',

  NEW_BOOKING_SUCCESS: 'NEW_BOOKING_SUCCESS',
  NEW_BOOKING_FAIL: 'NEW_BOOKING_FAIL',
  NEW_BOOKING_SUCCESS_AFTER: 'NEW_BOOKING_SUCCESS_AFTER',

  FLIGHT_STATS_SUCCESS: 'FLIGHT_STATS_SUCCESS',
  FLIGHT_STATS_FAIL: 'FLIGHT_STATS_FAIL',
  FLIGHT_STATS_SUCCESS_AFTER: 'FLIGHT_STATS_SUCCESS_AFTER',

  GET_BOOKING_SUCCESS: 'GET_BOOKING_SUCCESS',
  GET_BOOKING_FAIL: 'GET_BOOKING_FAIL',

  GET_HOTEL_BOOKING_SUCCESS: 'GET_BOOKING_SUCCESS',
  GET_HOTEL_BOOKING_FAIL: 'GET_BOOKING_FAIL',

  FORGET_PASSWORD_CODE_SEND_SUCCESS: 'FORGET_PASSWORD_CODE_SEND_SUCCESS',
  FORGET_PASSWORD_CODE_SEND_FAIL: 'FORGET_PASSWORD_CODE_SEND_FAIL',
  FORGET_PASSWORD_CODE_VERIFY_SUCCESS: 'FORGET_PASSWORD_CODE_VERIFY_SUCCESS',
  FORGET_PASSWORD_CODE_VERIFY_FAIL: 'FORGET_PASSWORD_CODE_VERIFY_FAIL',
  PASSWORD_RESET_SUCCESS: 'CONSTANTS.PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAIL: 'PASSWORD_RESET_FAIL',
  RESET_ALL_STATE: 'RESET_ALL_STATE',

  GET_COUNTRY_LIST_SUCCESS: 'GET_COUNTRY_LIST_SUCCESS',
  GET_COUNTRY_LIST_FAIL: 'GET_COUNTRY_LIST_FAIL',
  GET_AIRPORT_LIST_SUCCESS: 'GET_AIRPORT_LIST_SUCCESS',
  GET_AIRPORT_LIST_FAIL: 'GET_AIRPORT_LIST_FAIL',
  GET_SERVICE_AREA_LIST_SUCCESS: 'GET_SERVICE_AREA_LIST_SUCCESS',
  GET_SERVICE_AREA_LIST_FAIL: 'GET_SERVICE_AREA_LIST_FAIL',
  GET_BOOKING_CANCEL_REASON_SUCCEES: 'GET_BOOKING_CANCEL_REASON_SUCCEES',
  GET_BOOKING_CANCEL_REASON_FAIL: 'GET_BOOKING_CANCEL_REASON_FAIL',







  GET_INCOMING_PATIENTS_SUCCESS: 'GET_INCOMING_PATIENTS_SUCCESS',
  GET_INCOMING_PATIENTS_FAIL: 'GET_INCOMING_PATIENTS_FAIL'

};
